server:
  port: 8095
  servlet:
    context-path: /

spring:
  datasource:
    username: ${DB_USER_NAME:postgres}
    url: jdbc:postgresql://${DB_SERVICE_NAME:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:carvinu}
    password: ${DB_USER_PASSWORD:mahmoud}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
        default_schema: carvinu
